# Generated by Django 4.1.3 on 2022-11-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nResidencia', models.PositiveIntegerField()),
                ('titularResidencia', models.CharField(max_length=30)),
                ('tDestinatario', models.PositiveIntegerField()),
            ],
        ),
    ]
