# Generated by Django 4.1.3 on 2022-11-06 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residencia',
            options={'ordering': ['titularResidencia', 'nResidencia'], 'verbose_name': 'residencia', 'verbose_name_plural': 'residencias'},
        ),
        migrations.AlterModelTable(
            name='residencia',
            table='residencia',
        ),
    ]
