# Generated by Django 4.1.3 on 2022-11-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0002_alter_residencia_options_alter_residencia_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencia',
            name='nResidencia',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
