# Generated by Django 4.1.3 on 2022-11-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0003_alter_residencia_nresidencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residencia',
            options={'verbose_name': 'residencia', 'verbose_name_plural': 'residencias'},
        ),
    ]
