# Generated by Django 4.1.3 on 2022-11-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0004_alter_residencia_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencia',
            name='nResidencia',
            field=models.PositiveIntegerField(),
        ),
    ]
