# Generated by Django 4.1.3 on 2022-11-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('nResidencia', models.PositiveIntegerField()),
                ('nDestinatario', models.CharField(max_length=30)),
                ('tDestinatario', models.PositiveIntegerField()),
                ('estado', models.CharField(max_length=30)),
                ('comentario', models.CharField(max_length=100)),
            ],
        ),
    ]
