# Generated by Django 4.1.3 on 2022-11-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Correspondencia', '0002_alter_correspondencia_nresidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='estado',
            field=models.CharField(choices=[('Entregado', 'Entregado'), ('Pendiente', 'Pendiente'), ('Imposible realizacion', 'Imposible realizacion')], max_length=30),
        ),
    ]
